"""Add is_public and view_count fields

Revision ID: 15eb065b21d5
Revises: 27109bc650ef
Create Date: 2025-11-05 12:11:40.923092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15eb065b21d5'
down_revision = '27109bc650ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.create_index(batch_op.f('ix_keyword_categories_is_public'), ['is_public'], unique=False)

    with op.batch_alter_table('learning_keywords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('view_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_learning_keywords_is_public'), ['is_public'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_keywords_is_public'))
        batch_op.drop_column('view_count')
        batch_op.drop_column('is_public')

    with op.batch_alter_table('keyword_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keyword_categories_is_public'))
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
