"""Add profile_url to User model

Revision ID: 215537b026c3
Revises: 58d5bec4242d
Create Date: 2025-11-13 12:30:29.685693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215537b026c3'
down_revision = '58d5bec4242d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_url')

    # ### end Alembic commands ###
