"""Add slug and icon fields to KeywordCategory

Revision ID: 27109bc650ef
Revises: c61ec0b75ed4
Create Date: 2025-11-05 09:27:09.204694

"""
from alembic import op
import sqlalchemy as sa
import re


# revision identifiers, used by Alembic.
revision = '27109bc650ef'
down_revision = 'c61ec0b75ed4'
branch_labels = None
depends_on = None


def slugify(text):
    """Convert text to URL-friendly slug."""
    import unicodedata
    text = unicodedata.normalize('NFKD', text)
    text = text.encode('ascii', 'ignore').decode('ascii')
    text = re.sub(r'[^\w\s-]', '', text).strip().lower()
    text = re.sub(r'[-\s]+', '-', text)
    return text or text


def upgrade():
    # First add columns as nullable
    with op.batch_alter_table('keyword_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(), nullable=True))
    
    # Get connection to populate existing rows
    conn = op.get_bind()
    categories = conn.execute(sa.text("SELECT id, name FROM keyword_categories")).fetchall()
    
    # Default icons mapping for common categories
    icon_map = {
        '物理學': 'bi-lightning-charge',
        '化學': 'bi-droplet',
        '生物學': 'bi-tree',
        '數學': 'bi-calculator',
        '地球科學': 'bi-globe',
        '歷史': 'bi-clock-history',
        '地理': 'bi-geo-alt',
        '公民': 'bi-people',
        '國文': 'bi-book',
        '英文': 'bi-chat-text',
    }
    
    # Populate slug and icon for existing categories
    for category_id, name in categories:
        slug = slugify(name)
        icon = icon_map.get(name, 'bi-folder')
        conn.execute(
            sa.text("UPDATE keyword_categories SET slug = :slug, icon = :icon WHERE id = :id"),
            {"slug": slug, "icon": icon, "id": category_id}
        )
    
    # Now make columns non-nullable and add index
    with op.batch_alter_table('keyword_categories', schema=None) as batch_op:
        batch_op.alter_column('slug', nullable=False)
        batch_op.alter_column('icon', nullable=False)
        batch_op.create_index(batch_op.f('ix_keyword_categories_slug'), ['slug'], unique=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keyword_categories_slug'))
        batch_op.drop_column('icon')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
