"""Make LearningKeyword.author_id nullable to preserve keywords when deleting users

Revision ID: 376de3d1f684
Revises: 3098c435c89c
Create Date: 2025-11-12 08:47:30.427887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376de3d1f684'
down_revision = '3098c435c89c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_keywords', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_keywords', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
