"""add seo content fields to learning keywords

Revision ID: 506437f20ef8
Revises: 6e03639fa06a
Create Date: 2025-11-07 19:10:55.975623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506437f20ef8'
down_revision = '6e03639fa06a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_keywords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seo_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('seo_auto_generate', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_keywords', schema=None) as batch_op:
        batch_op.drop_column('seo_auto_generate')
        batch_op.drop_column('seo_content')

    # ### end Alembic commands ###
