"""add user active flag

Revision ID: 5292fb690208
Revises: 15eb065b21d5
Create Date: 2025-11-06 08:53:06.186930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5292fb690208'
down_revision = '15eb065b21d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_active',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
