"""Add author_name field to LearningKeyword for text-based author names

Revision ID: 58d5bec4242d
Revises: 376de3d1f684
Create Date: 2025-11-12 12:41:50.489172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d5bec4242d'
down_revision = '376de3d1f684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add author_name column to existing learning_keywords table
    with op.batch_alter_table('learning_keywords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_keywords', schema=None) as batch_op:
        batch_op.drop_column('author_name')
    # ### end Alembic commands ###
