"""add icon field to announcement banner

Revision ID: 6e03639fa06a
Revises: f5902a954927
Create Date: 2025-11-07 11:00:43.489967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e03639fa06a'
down_revision = 'f5902a954927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement_banners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(), nullable=False, server_default='bi-info-circle-fill'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement_banners', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
