"""Add position field to categories and keywords

Revision ID: 7b9267aaa234
Revises: dc7d633ddd50
Create Date: 2025-11-04 20:38:34.575617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9267aaa234'
down_revision = 'dc7d633ddd50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('learning_keywords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_keywords', schema=None) as batch_op:
        batch_op.drop_column('position')

    with op.batch_alter_table('keyword_categories', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
