"""remove avatar_url from users

Revision ID: 968a630e8785
Revises: d41921e1bb50
Create Date: 2025-11-08 11:27:26.430744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968a630e8785'
down_revision = 'd41921e1bb50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_hash', sa.String(), nullable=True))
        batch_op.drop_column('avatar_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(), nullable=True))
        batch_op.drop_column('avatar_hash')
    # ### end Alembic commands ###
