"""Add keyword aliases table

Revision ID: c61ec0b75ed4
Revises: 7b9267aaa234
Create Date: 2025-11-05 08:36:29.780720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61ec0b75ed4'
down_revision = '7b9267aaa234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['learning_keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keyword_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keyword_aliases_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keyword_aliases_slug'))

    op.drop_table('keyword_aliases')
    # ### end Alembic commands ###
