"""add_edit_logs_table

Revision ID: d41921e1bb50
Revises: 981fd5472dd3
Create Date: 2025-11-08 10:59:27.971301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41921e1bb50'
down_revision = '981fd5472dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'PUBLISH', 'UNPUBLISH', 'MOVE', 'REORDER', name='editlogaction'), nullable=False),
    sa.Column('target_type', sa.Enum('KEYWORD', 'CATEGORY', 'USER', 'ANNOUNCEMENT', 'NAVIGATION', 'FOOTER', 'SITE_SETTING', name='editlogtarget'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_edit_logs_target_type'), ['target_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_edit_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('learning_keywords', schema=None) as batch_op:
        batch_op.alter_column('seo_auto_generate',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_keywords', schema=None) as batch_op:
        batch_op.alter_column('seo_auto_generate',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('edit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_edit_logs_target_type'))
        batch_op.drop_index(batch_op.f('ix_edit_logs_action'))

    op.drop_table('edit_logs')
    # ### end Alembic commands ###
