"""remove color columns from announcement banner

Revision ID: f5902a954927
Revises: af1030b6210e
Create Date: 2025-11-07 10:28:03.955373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5902a954927'
down_revision = 'af1030b6210e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement_banners', schema=None) as batch_op:
        batch_op.drop_column('bg_color')
        batch_op.drop_column('text_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement_banners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_color', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('bg_color', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
